# Generated by Django 5.2.8 on 2025-11-29 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Applicantapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='linkedIn_profile',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='applicant',
            name='portfolio_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
