# Generated by Django 5.2.8 on 2025-11-29 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Applicantapp', '0002_applicant_linkedin_profile_applicant_portfolio_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='other_documents',
            field=models.FileField(blank=True, null=True, upload_to='documents/'),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='linkedIn_profile',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
