# Generated by Django 5.2.8 on 2025-11-30 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Applicantapp', '0003_applicant_other_documents_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='converted_images',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
