# Generated by Django 5.2.8 on 2025-12-13 15:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Applicantapp', '0004_applicant_converted_images'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='extracted_data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='applicant',
            name='location',
            field=models.CharField(blank=True, help_text='e.g., Nairobi, Remote', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='applicant',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='applicant',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='applicant_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
