# Generated by Django 5.2.8 on 2025-11-29 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Companyapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobadvertised',
            name='max_applicants',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
