# Generated by Django 5.2.8 on 2025-11-29 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Companyapp', '0002_jobadvertised_max_applicants'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobadvertised',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
