# Generated by Django 5.2.8 on 2025-11-30 00:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Companyapp', '0003_jobadvertised_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobadvertised',
            name='slug',
        ),
    ]
