# Generated by Django 5.2.8 on 2025-12-04 21:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Companyapp', '0005_remove_jobadvertised_keywords_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyticsReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_applicants', models.IntegerField(default=0)),
                ('avg_match_score', models.FloatField(default=0.0)),
                ('top_skills_found', models.JSONField(blank=True, default=list)),
                ('avg_experience_years', models.FloatField(default=0.0)),
                ('education_breakdown', models.JSONField(blank=True, default=dict)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to='Companyapp.jobadvertised')),
            ],
            options={
                'ordering': ['-generated_at'],
            },
        ),
    ]
