# Generated by Django 5.2.8 on 2025-11-30 22:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Applicantapp', '0004_applicant_converted_images'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResumeExtraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extracted_text', models.TextField(blank=True, null=True)),
                ('processed', models.BooleanField(default=False)),
                ('applicant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Applicantapp.applicant')),
            ],
        ),
    ]
