# Generated by Django 5.2.8 on 2025-11-30 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Extractionapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resumeextraction',
            name='education',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resumeextraction',
            name='projects',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resumeextraction',
            name='skills',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resumeextraction',
            name='work_experience',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
